### ISSUE TITLE
IllegalStateException when printing

### ISSUE THREAD

**Issue by blue2i-dev** [devinim/flutter-zsdk#4]
I want to print some ZPL from my flutter app to a Zebra printer (ZD420).
I'm using the example sample : 
``` dart
 print("Searching BL devices");
        List<ZebraBluetoothDevice> devices = await FlutterZsdk.discoverBluetoothDevices();
        print("Found ${devices.length} BL device(s)");
        devices.forEach((ZebraBluetoothDevice printer) {
          if (printer.friendlyName.toLowerCase().contains("zebra")) {
            print("Running print");
            printer.sendZplOverBluetooth(data);
          }
        });
```
The printer is well founded, the printing is starting, but right the way after that the app crashes and I get this : 
```
D/BluetoothSocket( 9904): close() this: android.bluetooth.BluetoothSocket@ec3503c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@603a1c5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e34171amSocket: android.net.LocalSocket@353f24b impl:android.net.LocalSocketImpl@f933428 fd:java.io.FileDescriptor@a819541, mSocketState: CONNECTED
D/BluetoothSocket( 9904): close() this: android.bluetooth.BluetoothSocket@ec3503c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@603a1c5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e34171amSocket: null, mSocketState: CLOSED
E/AndroidRuntime( 9904): FATAL EXCEPTION: Thread-3
E/AndroidRuntime( 9904): Process: com.example.b2icomm, PID: 9904
E/AndroidRuntime( 9904): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9904):    at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/AndroidRuntime( 9904):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime( 9904):    at tr.gen.devinim.flutterzsdk.FlutterZsdkPlugin$1.run(FlutterZsdkPlugin.java:267)
E/AndroidRuntime( 9904):    at java.lang.Thread.run(Thread.java:764)
D/BluetoothSocket( 9904): close() this: android.bluetooth.BluetoothSocket@ec3503c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@603a1c5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e34171amSocket: null, mSocketState: CLOSED
W/libEGL  ( 9904): eglTerminate() called w/ 1 objects remaining
W/FlutterJNI( 9904): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter/textinput. Response ID: 0
D/BluetoothSocket( 9904): close() this: android.bluetooth.BluetoothSocket@ec3503c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@603a1c5, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e34171amSocket: null, mSocketState: CLOSED
```
What could I do ? 
Thank  you very much for answering,
Best regards

**Comment by devinim** [comment]
Looks like something releated to this [https://github.com/flutter/flutter/issues/29092](url)

**Comment by MasulukeI** [comment]
Has anyone figured this one out?

**Comment by fgomezgr81** [comment]
Tienen un ejemplo que funcione para ver como lo implementaron o que pasos siguieron para poder implementar este codigo, ya que no me funciona me arroja el siguiente error y ya no que hacer:
Launching lib\main.dart on Ilium X510 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Multiple projects in this build have project directory 'C:\desarrollo\appFlutter\zebra\android': [:zebra, :]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

estoy utilizando una zebra imz220

**Comment by Jeffy6917** [comment]
Does anyone fix this error? i really need an answer

**Comment by IMasuluke** [comment]
@Jeffy6917 we managed to finally get around it by using the bluetooth_print plugin. We used 1.0.0. I see theres a 2.0.0 now. We had to substitute the receipt with actual ZPL syntax though. Not sure if it was our printers setup or the device only accepts ZPL but after we made that change we didn't have anymore crashes.

**Comment by Jeffy6917** [comment]
Do you hace an example in code that you can share to me?

**Comment by Jeffy6917** [comment]
Do you have an example in code that you can share to me?

**Comment by Jeffy6917** [comment]
After hours of debuggin i got the solution of this plugin:

1. first you have to download the plugin tou your PC and put in into your app file
2. then you have to import the fila with a path "./fluter-zsdk" in your puscpect.yaml
3. then in the plugin carpet go to android-src-main-flutersdkplugin.java
4. look the ZPLoverBluettooth function that is in the last lines of the code
5. comment the line of the result = "// result....
6. run tha app

**Comment by fgomezgr81** [comment]
> @Jeffy6917 logramos finalmente evitarlo usando el plugin bluetooth_print. Usamos 1.0.0. Veo que hay un 2.0.0 ahora. Tuvimos que sustituir el recibo por la sintaxis ZPL real sin embargo. No estoy seguro de si fue nuestra configuración de impresoras o el dispositivo sólo acepta ZPL, pero después de que hicimos ese cambio no teníamos más bloqueos.

Hello, could you help me to see how you did to solve your problem, what type of printers do you use since I use zebras

**Comment by Jeffy6917** [comment]
@fgomezgr81 Creo que hablas español, asi que te contesto en español, yo uso una impresora Zebra, debes explicarme de mejor forma cual es el error que tienes y yo te ayudare si puedo.

**Comment by fgomezgr81** [comment]
> @fgomezgr81 Creo que hablas español, asi que te contesto en español, yo uso una impresora Zebra, debes explicarme de mejor forma cual es el error que tienes y yo te ayudare si puedo.

Hola tengo una aplicacion en Flutter, y no he podido hacer que me funcione tu codigo para poder imprimir en una impresora zebra MZ220 que tengo, me podrias ayudar con esto. de hecho tengo una pregunta que te hice aqui mismo la que dice Doesn't work, ahi te coloque unas imagenes donde estoy implementando tu codigo. Actualmente estoy utilizando el package blue_thermal_printer, pero se descuadra todo el ticket que estoy generando ya que deja espacios y no he podido generar correctamente el codigo para poder hacer una buena impresion.

**Comment by Jeffy6917** [comment]
@fgomezgr81 tu error es que la carpeta flutter_zsdk la estas poniendo mal en tu carpeta de proyecto, te mostrare donde debe ir
![image](https://user-images.githubusercontent.com/32935443/98590870-11db7a80-2295-11eb-95f3-7a1e60b5d86d.png)
esa carpeta debe ir en la raiz del proyecto y debe ser instanciada en el pubspec.yaml de esta forma: 
![image](https://user-images.githubusercontent.com/32935443/98591691-31bf6e00-2296-11eb-8e98-85f8fe59f387.png)

**Comment by fgomezgr81** [comment]
> @fgomezgr81 tu error es que la carpeta flutter_zsdk la estas poniendo mal en tu carpeta de proyecto, te mostrare donde debe ir
> ![image](https://user-images.githubusercontent.com/32935443/98590870-11db7a80-2295-11eb-95f3-7a1e60b5d86d.png)
> esa carpeta debe ir en la raiz del proyecto y debe ser instanciada en el pubspec.yaml de esta forma:
> ![image](https://user-images.githubusercontent.com/32935443/98591691-31bf6e00-2296-11eb-8e98-85f8fe59f387.png)

De hecho coloque la referencia de esta forma.
![Captura de Pantalla 2020-11-10 a la(s) 10 57 03](https://user-images.githubusercontent.com/53118142/98705839-c207bc80-2343-11eb-9367-73f51b680fb6.png)

**Comment by Jeffy6917** [comment]
@fgomezgr81 No, descarga el repositorio de el, e importalo en tu carpeta, ya que el repositorio de el tiene un error, y hay que modificarlo uno mismo

**Comment by devinim** [comment]
Hey!
Thank you guys. I do not have time and energy to further develop this project. 
So if you discover any errors and fix them, you are welcome to commit and send me a pull request.

**Comment by fgomezgr81** [comment]
> @fgomezgr81 No, descarga el repositorio de el, e importalo en tu carpeta, ya que el repositorio de el tiene un error, y hay que modificarlo uno mismo

Hola ya pude hacer que funcionara solo que cuando mando el código ZPL, imprime tal cual el código ZPL y no imprime bien la label que necesito.

**Comment by Jeffy6917** [comment]
@fgomezgr81 haz una impresion del string que envias a la impresora y pruebalo en este sitio http://labelary.com/viewer.html, aca puedes ver como resultaria tu ZPL

**Comment by fgomezgr81** [comment]
> @fgomezgr81 haz una impresion del string que envias a la impresora y pruebalo en este sitio http://labelary.com/viewer.html, aca puedes ver como resultaria tu ZPL

este el codigo que trato de imprimir 👍 ^XA^FX Top section with logo, name and address.^CF0,60^FO120,50^FDDISLACVTA SA DE CV.^FS^CF0,30^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290^FS^FO220,155^FDPuerto Vallarta, Jal^FS^FO220,195^FDventas@dislac.com.mx^FS^FO220,235^FDTel.: 322 290 1396^FS^FO220,275^FDTel.: 322 290 2252^FS^FO50,315^GB700,1,3^FS^FX Second section with recipient address and permit information.^CFA,30^FO50,340^FDJohn Doe^FS^FO50,380^FD100 Main Street^FS^FO50,420^FDSpringfield TN 39021^FS^FO50,460^FDUnited States (USA)^FS^FO50,500^FDPedido^FS^FO50,540^GB700,1,3^FS^FX detalle del pedido^CFA,30^FO50,580^FDDescripcion del producto se colocara aqui^FS^FO50,630^FDCant.^FS^FO290,630^FDPrecio^FS^FO590,630^FDImporte^FS^FO50,680^FD100^FS^FO290,680^FD10000^FS^FO590,680^FD10000^FS^FX Importe total del pedido^CFA,30^FO300,750^FDImporte^FS^FO600,750^FD10000^FS^XZ
 
y a si se ve en la pagina que me pasaste.
![Captura](https://user-images.githubusercontent.com/53118142/99152000-b3cbe000-2664-11eb-8480-9c7c385711aa.PNG)

**Comment by Jeffy6917** [comment]
@fgomezgr81 enviame una foto del papel impreso

**Comment by fgomezgr81** [comment]
> @fgomezgr81 enviame una foto del papel impreso

![thumbnail_IMG_1947](https://user-images.githubusercontent.com/53118142/99213846-49b25880-2794-11eb-9edd-ddf89698a73c.jpg)

**Comment by Jeffy6917** [comment]
ok, el plugin recibe un string, ese string debe ser convertido, si me puedes mostrar el codigo donde envias el string, debe ser una cadena de estring multilinea

**Comment by fgomezgr81** [comment]
> ok, el plugin recibe un string, ese string debe ser convertido, si me puedes mostrar el codigo donde envias el string, debe ser una cadena de estring multilinea

Este es el codigo:

 _printZPL() async {
    String zpl = "";

    zpl += "^XA";
    zpl += "^FX Top section with logo, name and address.";
    zpl += "^CF0,60";
    zpl += "^FO120,50^FDDISLACVTA SA DE CV.^FS";
    zpl += "^CF0,30";
    zpl += "^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290^FS";
    zpl += "^FO220,155^FDPuerto Vallarta, Jal^FS";
    zpl += "^FO220,195^FDventas@dislac.com.mx^FS";
    zpl += "^FO220,235^FDTel.: 322 290 1396^FS";
    zpl += "^FO220,275^FDTel.: 322 290 2252^FS";
    zpl += "^FO50,315^GB700,1,3^FS";
    zpl += "^FX Second section with recipient address and permit information.";
    zpl += "^CFA,30";
    zpl += "^FO50,340^FDJohn Doe^FS";
    zpl += "^FO50,380^FD100 Main Street^FS";
    zpl += "^FO50,420^FDSpringfield TN 39021^FS";
    zpl += "^FO50,460^FDUnited States (USA)^FS";
    zpl += "^FO50,500^FDPedido^FS";
    zpl += "^FO50,540^GB700,1,3^FS";
    zpl += "^FX detalle del pedido";
    zpl += "^CFA,30";
    zpl += "^FO50,580^FDDescripcion del producto se colocara aqui^FS";
    zpl += "^FO50,630^FDCant.^FS";
    zpl += "^FO290,630^FDPrecio^FS";
    zpl += "^FO590,630^FDImporte^FS";
    zpl += "^FO50,680^FD100^FS";
    zpl += "^FO290,680^FD10000^FS";
    zpl += "^FO590,680^FD10000^FS";
    zpl += "^FX Importe total del pedido";
    zpl += "^CFA,30";
    zpl += "^FO300,750^FDImporte^FS";
    zpl += "^FO600,750^FD10000^FS";
    zpl += "^XZ";

    List<ZebraBluetoothDevice> devices =
        await FlutterZsdk.discoverBluetoothDevices();
    print("Found ${devices.length} BL device(s)");
    devices.forEach((ZebraBluetoothDevice printer) {
      if (printer.friendlyName.toLowerCase().contains("zebra")) {
        print("Running print");
        printer.sendZplOverBluetooth(zpl).then((t) {
          print("Printing complete");
        });
      }
    });
  }

**Comment by Jeffy6917** [comment]
![image](https://user-images.githubusercontent.com/32935443/99214690-78c9c980-2796-11eb-853f-a3cec4093a23.png)
@fgomezgr81 ok mira la imagen que te envio, arma el string con la comilla multilinea " ´ " y no le pongas " ; " al final de cada linea, no es necesario.

**Comment by fgomezgr81** [comment]
> ![image](https://user-images.githubusercontent.com/32935443/99214690-78c9c980-2796-11eb-853f-a3cec4093a23.png)
> @fgomezgr81 ok mira la imagen que te envio, arma el string con la comilla multilinea " ´ " y no le pongas " ; " al final de cada linea, no es necesario.

coloque asi el codigo

 zpl = `
    ^XA
    ^CF0,60
    ^FO120,50^FDDISLACVTA SA DE CV.^FS
    ^CF0,30
    ^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290^FS
    ^FO220,155^FDPuerto Vallarta, Jal^FS
    ^FO220,195^FDventas@dislac.com.mx^FS
    ^FO220,235^FDTel.: 322 290 1396^FS
    ^FO220,275^FDTel.: 322 290 2252^FS
    ^FO50,315^GB700,1,3^FS
    ^FX Second section with recipient address and permit information.
    ^CFA,30
    ^FO50,340^FDJohn Doe^FS
    ^FO50,380^FD100 Main Street^FS
    ^FO50,420^FDSpringfield TN 39021^FS
    ^FO50,460^FDUnited States (USA)^FS
    ^FO50,500^FDPedido^FS
    ^FO50,540^GB700,1,3^FS
    ^FX detalle del pedido
    ^CFA,30
    ^FO50,580^FDDescripcion del producto se colocara aqui^FS
    ^FO50,630^FDCant.^FS
    ^FO290,630^FDPrecio^FS
    ^FO590,630^FDImporte^FS
    ^FO50,680^FD100^FS
    ^FO290,680^FD10000^FS
    ^FO590,680^FD10000^FS
    ^FX Importe total del pedido
    ^CFA,30
    ^FO300,750^FDImporte^FS
    ^FO600,750^FD10000^FS
    ^XZ `;

pero me marca estos errores
![Captura1](https://user-images.githubusercontent.com/53118142/99215710-5e451f80-2799-11eb-87a2-c83d754abaca.PNG)

**Comment by Jeffy6917** [comment]
@fgomezgr81 

prueba asi: 

zpl = `^XA ^CF0,60 ^FO120,50^FDDISLACVTA SA DE CV.^FS ^CF0,30 ^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290^FS ^FO220,155^FDPuerto Vallarta, Jal^FS ^FO220,195^FDventas@dislac.com.mx^FS ^FO220,235^FDTel.: 322 290 1396^FS ^FO220,275^FDTel.: 322 290 2252^FS ^FO50,315^GB700,1,3^FS ^FX Second section with recipient address and permit information. ^CFA,30 ^FO50,340^FDJohn Doe^FS ^FO50,380^FD100 Main Street^FS ^FO50,420^FDSpringfield TN 39021^FS ^FO50,460^FDUnited States (USA)^FS ^FO50,500^FDPedido^FS ^FO50,540^GB700,1,3^FS ^FX detalle del pedido ^CFA,30 ^FO50,580^FDDescripcion del producto se colocara aqui^FS ^FO50,630^FDCant.^FS ^FO290,630^FDPrecio^FS ^FO590,630^FDImporte^FS ^FO50,680^FD100^FS ^FO290,680^FD10000^FS ^FO590,680^FD10000^FS ^FX Importe total del pedido ^CFA,30 ^FO300,750^FDImporte^FS ^FO600,750^FD10000^FS ^XZ`;

copia y pegalo asi como te lo pongo y prueba

**Comment by Jeffy6917** [comment]
@fgomezgr81  pero no te olvides de comenzar el stringo con la comilla multilinea

**Comment by Jeffy6917** [comment]
comienza el string con multiline y lo terminas con multilinea 
![image](https://user-images.githubusercontent.com/32935443/99216209-ba5c7380-279a-11eb-9a74-23f6a08ee9de.png)

**Comment by fgomezgr81** [comment]
> comienza el string con multiline y lo terminas con multilinea
> ![image](https://user-images.githubusercontent.com/32935443/99216209-ba5c7380-279a-11eb-9a74-23f6a08ee9de.png)
Si estoy colocando con multiline y aun asi me marca error:

![Captura](https://user-images.githubusercontent.com/53118142/99216448-51293000-279b-11eb-8d22-6143e743c647.PNG)

**Comment by Jeffy6917** [comment]
@fgomezgr81 es ciertooo
pardona, en dart el multilinea es distinto
intenta asi =

ZPL = 
***
^XA ^CF0,60 ^FO120,50^FDDISLACVTA SA DE CV.^FS ^CF0,30 ^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290^FS ^FO220,155^FDPuerto Vallarta, Jal^FS ^FO220,195^FDventas@dislac.com.mx^FS ^FO220,235^FDTel.: 322 290 1396^FS ^FO220,275^FDTel.: 322 290 2252^FS ^FO50,315^GB700,1,3^FS ^FX Second section with recipient address and permit information. ^CFA,30 ^FO50,340^FDJohn Doe^FS ^FO50,380^FD100 Main Street^FS ^FO50,420^FDSpringfield TN 39021^FS ^FO50,460^FDUnited States (USA)^FS ^FO50,500^FDPedido^FS ^FO50,540^GB700,1,3^FS ^FX detalle del pedido ^CFA,30 ^FO50,580^FDDescripcion del producto se colocara aqui^FS ^FO50,630^FDCant.^FS ^FO290,630^FDPrecio^FS ^FO590,630^FDImporte^FS ^FO50,680^FD100^FS ^FO290,680^FD10000^FS ^FO590,680^FD10000^FS ^FX Importe total del pedido ^CFA,30 ^FO300,750^FDImporte^FS ^FO600,750^FD10000^FS ^XZ
***;

**Comment by Jeffy6917** [comment]
@fgomezgr81  el multilineas en dart empieza con " *** " 3 asteriscos y termina con 3 asteriscos igual.

**Comment by fgomezgr81** [comment]
> @fgomezgr81 el multilineas en dart empieza con " *** " 3 asteriscos y termina con 3 asteriscos igual.

Ya coloque el texto a imprimir en mutilineas:

 zpl = '''^XA 
        ^CF0,60 
        ^FO120,50^FDDISLACVTA SA DE CV.
        ^FS ^CF0,30 
        ^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290
        ^FS ^FO220,155^FDPuerto Vallarta, Jal
        ^FS ^FO220,195^FDventas@dislac.com.mx
        ^FS ^FO220,235^FDTel.: 322 290 1396
        ^FS ^FO220,275^FDTel.: 322 290 2252
        ^FS ^FO50,315^GB700,1,3
        ^FS ^FX Second section with recipient address and permit information. 
        ^CFA,30 ^FO50,340^FDJohn Doe
        ^FS ^FO50,380^FD100 Main Street
        ^FS ^FO50,420^FDSpringfield TN 39021
        ^FS ^FO50,460^FDUnited States (USA)
        ^FS ^FO50,500^FDPedido
        ^FS ^FO50,540^GB700,1,3
        ^FS ^FX detalle del pedido 
        ^CFA,30 
        ^FO50,580^FDDescripcion del producto se colocara aqui
        ^FS ^FO50,630
        ^FDCant.^FS 
        ^FO290,630^FDPrecio
        ^FS ^FO590,630^FDImporte^FS 
        ^FO50,680
        ^FD100^FS 
        ^FO290,680^FD10000
        ^FS ^FO590,680
        ^FD10000^FS 
        ^FX Importe total del pedido 
        ^CFA,30 
        ^FO300,750
        ^FDImporte
        ^FS ^FO600,750^FD10000^FS 
        ^XZ''';

pero aun asi me sigue saliendo de esta forma:
![WhatsApp Image 2020-11-17 at 23 41 44](https://user-images.githubusercontent.com/53118142/99490082-bb260e80-292e-11eb-929a-dcc4ec20c2ac.jpeg)

**Comment by fgomezgr81** [comment]
> > @fgomezgr81 el multilineas en dart empieza con " *** " 3 asteriscos y termina con 3 asteriscos igual.
> 
> Ya coloque el texto a imprimir en mutilineas:
> 
> zpl = '''^XA
> ^CF0,60
> ^FO120,50^FDDISLACVTA SA DE CV.
> ^FS ^CF0,30
> ^FO120,115^FDCalle Sinaloa 374,Las Mojoneras,C.P. 48290
> ^FS ^FO220,155^FDPuerto Vallarta, Jal
> ^FS ^FO220,195^[FDventas@dislac.com.mx](mailto:FDventas@dislac.com.mx)
> ^FS ^FO220,235^FDTel.: 322 290 1396
> ^FS ^FO220,275^FDTel.: 322 290 2252
> ^FS ^FO50,315^GB700,1,3
> ^FS ^FX Second section with recipient address and permit information.
> ^CFA,30 ^FO50,340^FDJohn Doe
> ^FS ^FO50,380^FD100 Main Street
> ^FS ^FO50,420^FDSpringfield TN 39021
> ^FS ^FO50,460^FDUnited States (USA)
> ^FS ^FO50,500^FDPedido
> ^FS ^FO50,540^GB700,1,3
> ^FS ^FX detalle del pedido
> ^CFA,30
> ^FO50,580^FDDescripcion del producto se colocara aqui
> ^FS ^FO50,630
> ^FDCant.^FS
> ^FO290,630^FDPrecio
> ^FS ^FO590,630^FDImporte^FS
> ^FO50,680
> ^FD100^FS
> ^FO290,680^FD10000
> ^FS ^FO590,680
> ^FD10000^FS
> ^FX Importe total del pedido
> ^CFA,30
> ^FO300,750
> ^FDImporte
> ^FS ^FO600,750^FD10000^FS
> ^XZ''';
> 
> pero aun asi me sigue saliendo de esta forma:
> ![WhatsApp Image 2020-11-17 at 23 41 44](https://user-images.githubusercontent.com/53118142/99490082-bb260e80-292e-11eb-929a-dcc4ec20c2ac.jpeg)

Asi es como se esta enviado a la impresora:
![Captura](https://user-images.githubusercontent.com/53118142/99490565-b4e46200-292f-11eb-86a8-ee9ee553c29a.PNG)

**Comment by Jeffy6917** [comment]
@fgomezgr81 tal vez podamos hacer un hangput o un zoom en estos dias para ayudarte

**Comment by fgomezgr81** [comment]
> @fgomezgr81 tal vez podamos hacer un hangput o un zoom en estos dias para ayudarte

Te lo agradecería mucho este proyecto lo tengo atorado y les urge la impresion a mis amigos

**Comment by Jeffy6917** [comment]
@fgomezgr81 posiblemente este jueves en la noche este un poco libre!, me avisas!

**Comment by fgomezgr81** [comment]
> @fgomezgr81 posiblemente este jueves en la noche este un poco libre!, me avisas!

Si me parece bien, te paso mi correo dwprofesional@outlook.com para que me pases tu numero de celular y hablarte antes de conectarnos.

**Comment by Jeffy6917** [comment]
@fgomezgr81 este es el mio, me notificas pesgta17@gmail.com

**Comment by fgomezgr81** [comment]
> @fgomezgr81 este es el mio, me notificas [pesgta17@gmail.com](mailto:pesgta17@gmail.com)

Hola solo para saber si vas a poder hoy a las 3

**Comment by artoniaz** [comment]
Hey,
did you figure it out? Do you have a solution for this?

**Comment by artoniaz** [comment]
> After hours of debuggin i got the solution of this plugin:
> 
> 1. first you have to download the plugin tou your PC and put in into your app file
> 2. then you have to import the row with a path "./fluter-zsdk" in your puscpect.yaml
> 3. then in the plugin carpet go to android-src-main-flutersdkplugin.java
> 4. look the ZPLoverBluettooth function that is in the last lines of the code
> 5. comment the line of the result = "// result ....
> 6. run tha app

This has helped me a lot. Thank you very much. The only thing, I dk why I had to writte it this way: path: flutter-zsdk/
