### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by xakeppok** [devinim/flutter-zsdk#5]
I can't connect to printer using bt or wireless connection of flutter app. Flutter ZSDK can't found printer.

I/System.out( 9973): onMethodCall: discoverBluetoothDevices BluetoothDiscoverer.findPrinters
D/BluetoothAdapter( 9973): startDiscovery
I/System.out( 9973): ZebraBlDiscoverer: discoveryFinished.

Also i added my method for wireless from Zebra SDK
  private void sendZplOverTcp(String theIpAddress) throws ConnectionException {
         // Instantiate connection for ZPL TCP port at given address
         Connection thePrinterConn = new TcpConnection(theIpAddress, TcpConnection.DEFAULT_ZPL_TCP_PORT);
         try {
             thePrinterConn.open();
             String zplData = "^XA^FO20,20^A0N,25,25^FDThis is a ZPL test.^FS^XZ";
             thePrinterConn.write(zplData.getBytes());
         } catch (ConnectionException e) {
             e.printStackTrace();
         } finally {
             thePrinterConn.close();
         }
     }
and it still doesn't work
Error from my method:

I/System.out( 9973): onMethodCall: connectAndSend MI SUDA PRISHLI (test print)
I/System.out( 9973): TCP:192.168.139.136:6101
D/NetworkManagementSocketTagger( 9973): tagSocket(90) with statsTag=0xffffffff, statsUid=-1
W/System.err( 9973): com.zebra.sdk.comm.ConnectionException: Could not connect to device: NetworkOnMainThreadException

were you able to connect and print from flutter (ZD420)?

**Comment by devinim** [comment]
I did not tried to print over TCP, so I have no idea.
For BL, yes i can successfully print with IMZ320 both for iOS and Android. Actually i have an enterprise application which prints recieps.

Is it android or ios you are trying? And also, can you print with non flutter mobile application?

Finally, did you set neccesary permissons? (manifest? plist?).

BTW: It is a incomplete work, i have no intention to complete.

**Comment by fgomezgr81** [comment]
Cuales son los pasos para poder implementar flutter-zsdk, baje tu codigo de git pero no me funciona como le puedo hacer para implementarlo ya que tengo una app donde requier imprimir un ticket, me puede ayudar por favor

**Comment by devinim** [comment]
Sorry dude, english please.

**Comment by fgomezgr81** [comment]
What are the steps to implement flutter-zsdk, download your git code but it does not work for me as I can do to implement it since I have an application where I need to print a ticket, can you help me please

**Comment by devinim** [comment]
Hi there,
First of all you should add this package to your dependency list in pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_zsdk:
    git: https://github.com/devinim/flutter-zsdk
```

Then add fallowing permissions to your AndroidManifest.xml in (anroid/app/src/main)
```xml
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
```

Then try to run with this lines:
```dart
import 'package:flutter_zsdk/flutter_zsdk.dart';
//.....
List<ZebraBluetoothDevice> devices = await FlutterZsdk.discoverBluetoothDevices();
print("Found ${devices.length} BL device(s)");
devices.forEach((ZebraBluetoothDevice printer) {
  if (printer.friendlyName.toLowerCase().contains("zebra")) {
	print("Running print");
	printer.sendZplOverBluetooth(data).then((t) {
	  print("Printing complete");
	});
  }
});
```

**Comment by fgomezgr81** [comment]
Place the code as you tell me, but it does nothing, it just stays on the line where it looks for the devices, but from there it no longer happens.
![Captura de Pantalla 2020-11-08 a la(s) 18 32 23](https://user-images.githubusercontent.com/53118142/98488833-f1f27b00-21f0-11eb-8442-9680a3a5c3af.png)

After a while I got this:

![Captura de Pantalla 2020-11-08 a la(s) 18 34 34](https://user-images.githubusercontent.com/53118142/98488875-1f3f2900-21f1-11eb-95a5-1606100d2765.png)

**Comment by Sebastp** [comment]
Any news related to this?

**Comment by artoniaz** [comment]
The issue is due to the premissions. You need to use another package to give permission for your app to use blue. 
You need to do this before this line:
`wait FlutterZsdk
            .discoverBluetoothDevices()`
I use flutter blue for the permission.
