### ISSUE TITLE
Error while building for iOS

### ISSUE THREAD

**Issue by luis901101** [devinim/flutter-zsdk#6]
Currently I'm trying to use this plugin as a dependency of my project and I'm not able to build/run the project for iOS. For Android the project builds/run just fine, but for iOS I get the following error:

>Running Xcode build...
Xcode build done.                                            3.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-02-07 12:20:44.583 xcodebuild[29722:10555466]  DTDeviceKit: deviceType from 00008006-001C498E2206002E was NULL
    2020-02-07 12:20:44.584 xcodebuild[29722:10555578]  DTDeviceKit: deviceType from 00008006-001C498E2206002E was NULL
    2020-02-07 12:20:44.677 xcodebuild[29722:10555344] [MT] DTDeviceKit: deviceType from 00008006-001C498E2206002E was NULL
    2020-02-07 12:20:44.681 xcodebuild[29722:10555344] [MT] DTDeviceKit: deviceType from 00008006-001C498E2206002E was NULL
    2020-02-07 12:20:44.685 xcodebuild[29722:10555344] [MT] DTDeviceKit: deviceType from 00008006-001C498E2206002E was NULL
    ** BUILD FAILED **

>Xcode's output:
↳
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_SGD", referenced from:
          objc-class-ref in FlutterZsdkPlugin.o
      "_OBJC_CLASS_$_MfiBtPrinterConnection", referenced from:
          objc-class-ref in FlutterZsdkPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

>Could not build the precompiled application for the device.

>Error launching application on iDevice.

**It's something related to the static library, I mean the classes from inside the static library are not accessible... for the specified architecture**

Note: Note: I opened the flutter_zsdk plugin as a project in Android Studio and I were able to build/run the example_app for both Android and iOS without any extra action… just opened the project, and build and everything worked fine.

Is there something that I have to set in the iOS project configuration in order to be able to build properly.

**Comment by devinim** [comment]
Hi there,

You should import zsdk.a file to project in xCode.

**Comment by luis901101** [comment]
Hi, thanks for your answer.
I have tried to do that but I’m new with iOS and XCode, in fact I opened 2 XCodes one with flutter-zsdk example and another with my iOS project in order to make the same configurations in both projects but no look.
When yo say import zsdk.a file you mean “Link Static Library”?
Could you please give me some specific directions??? I have the feeling I’m missing something very simple that I don’t know.
Thanks in advance.

**Comment by devinim** [comment]
Hi,
You should follow these steps. It should work.
Click on Runner target, in "General" tab, scroll down to "Linked Frameworks And Libraries" section. Click on plus icon, in opening window, click on "Add other" button, select zsdk.a file from your filesystem. (it should be somewhere in project folder, or you can just download it from the repository: flutter-zsdk/ios/Libs/zsdk )

Normally, you should not do this. Plugin should register this library. But i realy don't understand iOS.

**Comment by luis901101** [comment]
I will try that again... I have done it before, from Linked Frameworks in General tab and from Link Static Library from Build Phases tab... with no luck.
I think it’s something related to the **headers** from zsdk.a library.
I don’t understand iOS either...
Thanks again for your answer.

**Comment by luis901101** [comment]
Finally I found a solution.
I commented the **use_frameworks!** from Podfile and everything worked fine...
