### ISSUE TITLE
can't build ios

### ISSUE THREAD

**Issue by daydreamer106** [devinim/flutter-zsdk#7]
I got following error

Undefined symbols for architecture x86_64:
"OBJC_CLASS$_SGD", referenced from:
objc-class-ref in FlutterZsdkPlugin.o
"OBJC_CLASS$_MfiBtPrinterConnection", referenced from:
objc-class-ref in FlutterZsdkPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kfliew** [comment]
same here, any solution for that?

**Comment by richardzamora** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/47605282/114254069-e8716880-9972-11eb-81f3-23edaf4ae620.png)

**Comment by devinim** [comment]
Hey,
I am not maintain this project. But if i guess from error message, you should try a different architecture like armv7.
